---
name: "auto-release"

on:
  push:
    branches:
      - main
    paths:
      - assets/**
      - data/**
      - pack.mcmeta
      - .github/workflows/**
      
  workflow_dispatch:

jobs:
  auto-release:
    name: "Latest Release"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      
      - uses: superjaja05/action-zip@v1
        with:
          dest: jajasgates_resourcepack.zip
          recursive: false
          files: assets, ./pack.mcmeta
          
      - uses: actions/upload-artifact@v4
        with:
          name: resourcepack
          path: ${{ github.workspace }}/jajasgates_resourcepack.zip

      - uses: superjaja05/action-zip@v1
        with:
          dest: jajasgates_datapack.zip
          recursive: false
          files: data, ./pack.mcmeta
          
      - uses: actions/upload-artifact@v4
        with:
          name: datapack
          path: ${{ github.workspace }}/jajasgates_datapack.zip

      - uses: superjaja05/action-zip@v1
        with:
          dest: jajasgates_RP_and_DP.zip
          recursive: false
          files: jajasgates_resourcepack.zip, jajasgates_datapack.zip

      - uses: actions/upload-artifact@v4
        with:
          name: rp_and_dp
          path: ${{ github.workspace }}/jajasgates_RP_and_DP.zip

      - uses: superjaja05/action-zip@v1
        with:
          dest: jajasgates_kubejs.zip
          recursive: false
          files: assets, data

      - name: Delete tag and release
        id: delete_release
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete drafts
        id: delete_draft
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: "Auto Release"
          tag_name: latest
          draft: false
          prerelease: false
          files: |
            jajasgates_resourcepack.zip
            jajasgates_datapack.zip
            jajasgates_RP_and_DP.zip
            jajasgates_kubejs.zip



